### ISSUE TITLE
i am get this issue 

### ISSUE THREAD

**Issue by buck311** [anti-natalist/ANI-Youtube-Comment-Bot#1]
python youtube_auto_commentor.py
Traceback (most recent call last):
  File "youtube_auto_commentor.py", line 36, in <module>
    driver = webdriver.Chrome(ChromeDriverManager().install())
NameError: name 'ChromeDriverManager' is not defined

**Comment by anti-natalist** [comment]
> python youtube_auto_commentor.py
> Traceback (most recent call last):
> File "youtube_auto_commentor.py", line 36, in
> driver = webdriver.Chrome(ChromeDriverManager().install())
> NameError: name 'ChromeDriverManager' is not defined

So Sorry for the inconvenience caused  @buck311 
that was surely a bug. Thank you so much for pointing out !
I've fixed it. Hope it is resolved now !
Enjoy :)

**Comment by anti-natalist** [comment]
@buck311 Feel free to either report any further bugs or else kindly close this issue if you feel satisfied with the fix ..
Thanks :) Cheers 👍
